version: '3'

services:
  postgresql-repmgr-0:
    image: bitnami/postgresql-repmgr:latest
    container_name: postgresql-repmgr-0
    networks:
      - backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_USERNAME=pg
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_DATABASE=pg
      - REPMGR_PASSWORD=XLrootJYD713
      - REPMGR_PRIMARY_HOST=postgresql-repmgr-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgresql-repmgr-0,postgresql-repmgr-1,postgresql-repmgr-2:5432
      - REPMGR_NODE_NAME=postgresql-repmgr-0
      - REPMGR_NODE_NETWORK_NAME=postgresql-repmgr-0
      - REPMGR_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/postgresql-repmgr-0:/bitnami/postgresql/data
      - ./conf/:/bitnami/postgresql/conf/conf.d/
  postgresql-repmgr-1:
    image: bitnami/postgresql-repmgr:latest
    container_name: postgresql-repmgr-1
    networks:
      - backend
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_USERNAME=pg
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_DATABASE=pg
      - REPMGR_PASSWORD=XLrootJYD713
      - REPMGR_PRIMARY_HOST=postgresql-repmgr-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgresql-repmgr-0,postgresql-repmgr-1,postgresql-repmgr-2:5432
      - REPMGR_NODE_NAME=postgresql-repmgr-1
      - REPMGR_NODE_NETWORK_NAME=postgresql-repmgr-1
      - REPMGR_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/postgresql-repmgr-1:/bitnami/postgresql/data
      - ./conf/:/bitnami/postgresql/conf/conf.d/
  postgresql-repmgr-2:
    image: bitnami/postgresql-repmgr:latest
    container_name: postgresql-repmgr-2
    networks:
      - backend
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=XLrootJYD713
      - POSTGRESQL_USERNAME=pg
      - POSTGRESQL_PASSWORD=XLrootJYD713
      - POSTGRESQL_DATABASE=pg
      - REPMGR_PASSWORD=XLrootJYD713
      - REPMGR_PRIMARY_HOST=postgresql-repmgr-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgresql-repmgr-0,postgresql-repmgr-1,postgresql-repmgr-2:5432
      - REPMGR_NODE_NAME=postgresql-repmgr-2
      - REPMGR_NODE_NETWORK_NAME=postgresql-repmgr-2
      - REPMGR_PORT_NUMBER=5432
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/postgresql-repmgr-2:/bitnami/postgresql/data
      - ./conf/:/bitnami/postgresql/conf/conf.d/

networks:
  backend:
    external: true
