version: '3'
services:

  kafka-zookeeper0:
    container_name: kafka-zookeeper0
    image: bitnami/zookeeper:3.7.0
    networks:
      - backend
    volumes:
      - /opt/volumes/kafka-zookeeper0:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=0
      - ZOO_SERVERS=kafka-zookeeper0:2888:3888,kafka-zookeeper1:2888:3888,kafka-zookeeper2:2888:3888,kafka-zookeeper3:2888:3888
  kafka-zookeeper1:
    container_name: kafka-zookeeper1
    image: bitnami/zookeeper:3.7.0
    networks:
      - backend
    volumes:
      - /opt/volumes/kafka-zookeeper1:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=kafka-zookeeper0:2888:3888,kafka-zookeeper1:2888:3888,kafka-zookeeper2:2888:3888,kafka-zookeeper3:2888:3888
  kafka-zookeeper2:
    container_name: kafka-zookeeper2
    image: bitnami/zookeeper:3.7.0
    networks:
      - backend
    volumes:
      - /opt/volumes/kafka-zookeeper2:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=kafka-zookeeper0:2888:3888,kafka-zookeeper1:2888:3888,kafka-zookeeper2:2888:3888,kafka-zookeeper3:2888:3888
  kafka-zookeeper3:
    container_name: kafka-zookeeper3
    image: bitnami/zookeeper:3.7.0
    networks:
      - backend
    volumes:
      - /opt/volumes/kafka-zookeeper3:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=kafka-zookeeper0:2888:3888,kafka-zookeeper1:2888:3888,kafka-zookeeper2:2888:3888,kafka-zookeeper3:2888:3888
  kafka-cluster0:
    container_name: kafka-cluster0
    image: bitnami/kafka:3.0.0
    networks:
      - backend
    depends_on:
      - kafka-zookeeper0
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/kafka-cluster0:/bitnami/kafka/data
      - /opt/volumes/extra:/extra
  kafka-cluster1:
    container_name: kafka-cluster1
    image: bitnami/kafka:3.0.0
    networks:
      - backend
    depends_on:
      - kafka-zookeeper0
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/kafka-cluster1:/bitnami/kafka/data
      - /opt/volumes/extra:/extra
  kafka-cluster2:
    container_name: kafka-cluster2
    image: bitnami/kafka:3.0.0
    networks:
      - backend
    depends_on:
      - kafka-zookeeper0
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/kafka-cluster2:/bitnami/kafka/data
      - /opt/volumes/extra:/extra
  kafka-cluster3:
    container_name: kafka-cluster3
    image: bitnami/kafka:3.0.0
    networks:
      - backend
    depends_on:
      - kafka-zookeeper0
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - '9095:9095'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9095
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/kafka-cluster3:/bitnami/kafka/data
      - /opt/volumes/extra:/extra
#  kafka-exporter:
#    container_name: kafka-exporter
#    image: bitnami/kafka-exporter
#    networks:
#      - backend
#    depends_on:
#      - kafka-cluster0
#      - kafka-cluster1
#      - kafka-cluster2
#      - kafka-cluster3
#    ports:
#      - '9308:9308'
#    command: --kafka.server=kafka-cluster0:9092,kafka-cluster1:9093,kafka-cluster2:9094,kafka-cluster3:9095

networks:
  backend:
    external: true
