version: '3'
services:

  clickhouse-zookeeper:
    container_name: clickhouse-zookeeper
    image: bitnami/zookeeper
    networks:
      - backend
    volumes:
      - /opt/volumes/clickhouse-zookeeper/data:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  clickhouse-shard0-replica0:
    container_name: clickhouse-shard0-replica0
    image: clickhouse-shard0-replica0
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard0-replica0/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard0-replica0/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

  clickhouse-shard0-replica1:
    container_name: clickhouse-shard0-replica1
    image: clickhouse-shard0-replica1
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard0-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard0-replica1/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

  clickhouse-shard1-replica0:
    container_name: clickhouse-shard1-replica0
    image: clickhouse-shard1-replica0
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8125:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard1-replica0/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard1-replica0/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

  clickhouse-shard1-replica1:
    container_name: clickhouse-shard1-replica1
    image: clickhouse-shard1-replica1
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8126:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard1-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard1-replica1/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

  clickhouse-shard2-replica0:
    container_name: clickhouse-shard2-replica0
    image: clickhouse-shard2-replica0
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8127:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard2-replica0/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard2-replica0/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

  clickhouse-shard2-replica1:
    container_name: clickhouse-shard2-replica1
    image: clickhouse-shard2-replica1
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8128:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard2-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard2-replica1/log:/var/log/clickhouse-server
      - /opt/volumes/extra:/extra

networks:
  backend:
    external: true
