version: "3"

services:
  redis-master:
    image: bitnami/redis:6.2.6
    container_name: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - /opt/volumes/redis-master:/bitnami/redis/data
      - /opt/volumes/extra:/extra
  redis-slave0:
    image: bitnami/redis:6.2.6
    container_name: redis-slave0
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - REDIS_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - backend
    volumes:
      - /opt/volumes/redis-slave0:/bitnami/redis/data
      - /opt/volumes/extra:/extra
  redis-slave1:
    image: bitnami/redis:6.2.6
    container_name: redis-slave1
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - REDIS_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    networks:
      - backend
    volumes:
      - /opt/volumes/redis-slave1:/bitnami/redis/data
      - /opt/volumes/extra:/extra
  redis-slave2:
    image: bitnami/redis:6.2.6
    container_name: redis-slave2
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - REDIS_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    ports:
      - "6382:6379"
    depends_on:
      - redis-master
    networks:
      - backend
    volumes:
      - /opt/volumes/redis-slave2:/bitnami/redis/data
      - /opt/volumes/extra:/extra
  redis-sentinel0:
    image: bitnami/redis-sentinel:6.2.6
    container_name: redis-sentinel0
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    depends_on:
      - redis-master
      - redis-slave0
      - redis-slave1
      - redis-slave2
    ports:
      - "26379:26379"
    networks:
      - backend
  redis-sentinel1:
    image: bitnami/redis-sentinel:6.2.6
    container_name: redis-sentinel1
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    depends_on:
      - redis-master
      - redis-slave0
      - redis-slave1
      - redis-slave2
    ports:
      - "26380:26379"
    networks:
      - backend
  redis-sentinel2:
    image: bitnami/redis-sentinel:6.2.6
    container_name: redis-sentinel2
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=XLrootJYD713
      - TZ=Asia/Shanghai
    depends_on:
      - redis-master
      - redis-slave0
      - redis-slave1
      - redis-slave2
    ports:
      - "26381:26379"
    networks:
      - backend

networks:
  backend:
    external: true
