version: '3'
services:

  goland:
    image: jetbrains/projector-goland:2020.3-projector-v1.4.0
    container_name: goland
    hostname: goland
    ports:
      - "8888:8887"
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai

networks:
  backend:
    external: true
