version: '3'

services:
  spark-master:
    image: bitnami/spark:3.3.1
    container_name: spark-master
    networks:
      - backend
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - TZ=Asia/Shanghai
    ports:
      - '8078:8080'
  spark-worker1:
    image: bitnami/spark:3.3.1
    container_name: spark-worker1
    networks:
      - backend
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=${MEM}G
      - SPARK_WORKER_CORES=${NUM}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - TZ=Asia/Shanghai
  spark-worker2:
    image: bitnami/spark:3.3.1
    container_name: spark-worker2
    networks:
      - backend
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=${MEM}G
      - SPARK_WORKER_CORES=${NUM}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - TZ=Asia/Shanghai

networks:
  backend:
    external: true
