version: '3'

services:
  clickhouse-zookeeper:
    container_name: clickhouse-zookeeper
    image: bitnami/zookeeper:3.7.0
    networks:
      - backend
    volumes:
      - /opt/volumes/clickhouse-zookeeper:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai

  clickhouse-shard1-replica1:
    container_name: clickhouse-shard1-replica1
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard1-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard1-replica1/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-00-0.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

  clickhouse-shard1-replica2:
    container_name: clickhouse-shard1-replica2
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard1-replica2/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard1-replica2/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-00-1.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

  clickhouse-shard2-replica1:
    container_name: clickhouse-shard2-replica1
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8125:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard2-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard2-replica1/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-01-0.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

  clickhouse-shard2-replica2:
    container_name: clickhouse-shard2-replica2
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8126:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard2-replica2/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard2-replica2/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-01-1.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

  clickhouse-shard3-replica1:
    container_name: clickhouse-shard3-replica1
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8127:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard3-replica1/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard3-replica1/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-02-0.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

  clickhouse-shard3-replica2:
    container_name: clickhouse-shard3-replica2
    image: yandex/clickhouse-server:22.1.2.2
    networks:
      - backend
    depends_on:
      - clickhouse-zookeeper
    ports:
      - "8128:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /opt/volumes/clickhouse-shard3-replica2/lib:/var/lib/clickhouse
      - /opt/volumes/clickhouse-shard3-replica2/log:/var/log/clickhouse-server
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config-02-1.xml:/etc/clickhouse-server/config.xml
    environment:
      - TZ=Asia/Shanghai

networks:
  backend:
    external: true
