version: '3'
services:

  kafka-zookeeper:
    container_name: kafka-zookeeper
    image: bitnami/zookeeper
    networks:
      - backend
    volumes:
      - /opt/volumes/kafka-zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-cluster1:
    container_name: kafka-cluster1
    image: bitnami/kafka
    networks:
      - backend
    depends_on:
      - kafka-zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/volumes/kafka-cluster1:/bitnami
      - /opt/volumes/extra:/extra

  kafka-cluster2:
    container_name: kafka-cluster2
    image: bitnami/kafka
    networks:
      - backend
    depends_on:
      - kafka-zookeeper
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/volumes/kafka-cluster2:/bitnami
      - /opt/volumes/extra:/extra

  kafka-cluster3:
    container_name: kafka-cluster3
    image: bitnami/kafka
    networks:
      - backend
    depends_on:
      - kafka-zookeeper
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/volumes/kafka-cluster3:/bitnami
      - /opt/volumes/extra:/extra

#  kafka-exporter:
#    container_name: kafka-exporter
#    image: bitnami/kafka-exporter
#    networks:
#      - backend
#    depends_on:
#      - kafka-cluster1
#      - kafka-cluster2
#      - kafka-cluster3
#    ports:
#      - '9308:9308'
#    command: --kafka.server=kafka-cluster1:9092,kafka-cluster2:9093,kafka-cluster3:9094

networks:
  backend:
    external: true
