version: '3'
services:

  mosquitto-node:
    container_name: mosquitto-node
    build: ctx
    image: mosquitto-node
    networks:
      - backend
    ports:
      - '1883:1883'
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/volumes/mosquitto-node:/mosquitto

networks:
  backend:
    external: true
