version: '3'
services:

  elasticsearch-cluster1:
    image: elasticsearch-server
    container_name: elasticsearch-cluster1
    privileged: true
    environment:
      - node.name=elasticsearch-cluster1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-cluster2,elasticsearch-cluster3
      - cluster.initial_master_nodes=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/volumes/elasticsearch-cluster1/data:/usr/share/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9201:9200"
    networks:
      - backend

  elasticsearch-cluster2:
    image: elasticsearch-server
    container_name: elasticsearch-cluster2
    privileged: true
    environment:
      - node.name=elasticsearch-cluster2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-cluster1,elasticsearch-cluster3
      - cluster.initial_master_nodes=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/volumes/elasticsearch-cluster2/data:/usr/share/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9202:9200"
    networks:
      - backend

  elasticsearch-cluster3:
    image: elasticsearch-server
    container_name: elasticsearch-cluster3
    privileged: true
    environment:
      - node.name=elasticsearch-cluster3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-cluster1,elasticsearch-cluster2
      - cluster.initial_master_nodes=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/volumes/elasticsearch-cluster3/data:/usr/share/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9203:9200"
    networks:
      - backend

networks:
  backend:
    external: true
