version: '3'
services:

  elasticsearch-cluster0:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster0
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster0,elasticsearch-cluster1,elasticsearch-cluster2
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster0
      - TZ=Asia/Shanghai
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster0:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9200:9200"
    networks:
      - backend
  elasticsearch-cluster1:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster1
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster0,elasticsearch-cluster1,elasticsearch-cluster2
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster1
      - TZ=Asia/Shanghai
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster1:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9201:9200"
    networks:
      - backend
  elasticsearch-cluster2:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster2
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster0,elasticsearch-cluster1,elasticsearch-cluster2
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster2
      - TZ=Asia/Shanghai
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster2:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9202:9200"
    networks:
      - backend
  elasticsearch-kibana:
    image: bitnami/kibana:7.14.1
    container_name: elasticsearch-kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-cluster0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/volumes/elasticsearch-kibana:/bitnami/kibana/data
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch-cluster0
      - elasticsearch-cluster1
      - elasticsearch-cluster2

networks:
  backend:
    external: true
