version: '3'
services:

  elasticsearch-cluster1:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster1
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster1
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster1/data:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9200:9200"
    networks:
      - backend

  elasticsearch-cluster2:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster2
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster2
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster2/data:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9201:9200"
    networks:
      - backend

  elasticsearch-cluster3:
    image: bitnami/elasticsearch:7.14.1
    container_name: elasticsearch-cluster3
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-cluster1,elasticsearch-cluster2,elasticsearch-cluster3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-cluster3
    volumes:
      - ../plugins/elasticsearch-analysis-ik-7.14.1.zip:/bitnami/elasticsearch/plugins/analysis-ik-7.14.1.zip
      - /opt/volumes/elasticsearch-cluster3/data:/bitnami/elasticsearch/data
      - /opt/volumes/extra:/extra
    ports:
      - "9202:9200"
    networks:
      - backend

networks:
  backend:
    external: true
